version: "3.7"

services:
    backend:
        build: ./backend
        container_name:  backend
        restart: always
        environment:
            - FRONTEND_URL_ONE=http://localhost:8080/ 
            - FRONTEND_URL_TWO=http://127.0.0.1:8080/ 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - './backend:/backend'
        ports:
            - "5000:5000"
        expose:
            - 5000
        links:
            - db

    db:
        image: mongo:latest
        hostname: mongodb
        environment:
            - MONGO_INITDB_DATABASE=urls_db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
        ports:
            - 27017:27017
    
    frontend:
        build: ./frontend
        container_name:  frontend
        restart: always
        volumes:
            - './frontend:/frontend'
        ports:
            - "8080:8080"
        expose: 
            - 8080